// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `myservice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package rpc.ice.hello;

public interface MyServicePrx extends Ice.ObjectPrx
{
    public String hellowd();

    public String hellowd(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_hellowd();

    public Ice.AsyncResult begin_hellowd(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_hellowd(Ice.Callback __cb);

    public Ice.AsyncResult begin_hellowd(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_hellowd(Callback_MyService_hellowd __cb);

    public Ice.AsyncResult begin_hellowd(java.util.Map<String, String> __ctx, Callback_MyService_hellowd __cb);

    public Ice.AsyncResult begin_hellowd(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_hellowd(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_hellowd(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_hellowd(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_hellowd(Ice.AsyncResult __result);
}
