// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `myservice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package rpc.ice.hello;

public interface MyService extends Ice.Object,
                                   _MyServiceOperations, _MyServiceOperationsNC
{
    public static final String ice_staticId = "::hello::MyService";

    public static final long serialVersionUID = 1445570550L;
}
